apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-green
  name: blue-green
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blue-green
  strategy:                 # Default Strategy
    rollingUpdate:          # RollingUpdate is Default in K8S
      maxSurge: 25%         # Default Value
      maxUnavailable: 25%   # Default Value
    type: RollingUpdate     # Default Type
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
        - image: default
          name: blue-green-image
          resources: {}
status: {}
