apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blue-green
  name: blue-green
spec:
  clusterIP: None
  selector:
    app: blue-green
  type: ClusterIP
status:
  loadBalancer: {}