apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-green
  name: blue-green
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green
  strategy: {}
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
        - image: default
          name: blue-green-image
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: "2000"
              memory: "4Gb"
            requests:
              cpu: "1000"
              memory: "2Gb"
          volumeMounts:
            - mountPath: /config
              name: bg-config-dev
      volumes:
        - name: bg-config-dev
          configMap:
            name: bg-config-dev